### ISSUE TITLE
NetHack 3.6.0 crash on saved game load

### ISSUE THREAD

**Issue by summonthethunder** [gurrhack/NetHack-Android#16] opened 2015-12-29 23:05 UTC
NetHack 3.6.0 port crashes when trying to load a saved game, forcing a close.  Have completely uninstalled follow by a reinstall with same problem.  Droid Maxx, Android 4.4.4.

**Comment by gurrhack** [comment] 2015-12-29 23:20
Could you send me a crash dump? The easiest way to do that is to click the "Report" button in the crash dialog. If you don't see any report button can you contact me directly at martin.gurr@gmail.com?

**Comment by summonthethunder** [comment] 2015-12-29 23:23
Ok will do.

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Could you send me a crash dump? The easiest way to do that is to click the "Report" button in the crash dialog. If you don't see any report button can you contact me directly at martin.gurr@gmail.com<mailto:martin.gurr@gmail.com>?

-

**Comment by summonthethunder** [comment] 2015-12-29 23:26
Crash report sent via Google Play.  Let me know if you get it, or anything else you might need.  Thank you so much for the awesome port!  Been playing it for years!

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Could you send me a crash dump? The easiest way to do that is to click the "Report" button in the crash dialog. If you don't see any report button can you contact me directly at martin.gurr@gmail.com<mailto:martin.gurr@gmail.com>?

-

**Comment by gurrhack** [comment] 2015-12-29 23:43
I got it. It might take some time to figure out because it looks "weird". So don't expect a fix this year! I suggest you revert to the previous version in the meantime: https://github.com/gurrhack/NetHack-Android/releases/tag/v1.4.0

**Comment by summonthethunder** [comment] 2015-12-29 23:59
Looks "wierd" aye, got it!  Thank you for checking it out.

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


I got it. It might take some time to figure out because it looks "weird". So don't expect a fix this year! I suggest you revert to the previous version in the meantime: https://github.com/gurrhack/NetHack-Android/releases/tag/v1.4.0

**Comment by gurrhack** [comment] 2015-12-30 13:23
Did you change anything in the settings before it started to crash?

**Comment by summonthethunder** [comment] 2015-12-30 18:43
I turned off autopickup and showexp in the in-game settings (letter O), and I cycled through the tilesets before I settled on DawnHack.  Those were the only changes.
________________________________

**Comment by summonthethunder** [comment] 2015-12-30 18:49
I turned off autopickup and showexp via the in-game menu (letter O), and I cycled through the tilesets to check them out, settling on DawnHack.  Those were the only changes.

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Did you change anything in the settings before it started to crash?

-

**Comment by mueer01** [comment] 2015-12-31 12:38
Hi Martin,

since the automatic upgrade to 3.6.0 the old saved file coudn't be opened anymore.
So I copied it, installed 1.4.0 and restored the file. It works.
Pheww! That was close!
But how can I prevent, that 3.6.0 will be installed automatically again in the night?
My current game will take some more time.

Regards,
Erhard

**Comment by gurrhack** [comment] 2015-12-31 13:22
If you downloaded and installed the apk from this site it will never update automatically. Only apps installed through Google Play does that. You can disable it in Google Play settings

**Comment by summonthethunder** [comment] 2015-12-31 14:46
Hello Martin,

My wife has a Nexus 9 android tablet running the new 6.0.1 OS, and your NetHack 3.6.0 app runs fine on hers after updating the old app.  Not sure if that helps or not, but I figured I'd put it out there.

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


If you downloaded and installed the apk from this site it will never update automatically. Only apps installed through Google Play does that. You can disable it in Google Play settings

-

**Comment by gurrhack** [comment] 2015-12-31 14:55
I've managed to reproduce it on an old Samsung. Still not sure what's causing it though.

**Comment by summonthethunder** [comment] 2015-12-31 15:08
Well, atleast it wasn't something I randomly did!  Maybe older Android OS's have a problem with the various rewritten code in the new 3.6.0.  Thank you again for working on this!

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


I've managed to reproduce it on an old Samsung. Still not sure what's causing it though.

-

**Comment by gurrhack** [comment] 2016-01-01 18:34
Are you willing to try the new release for a while and see if it also crashes?
Keep in mind that you will loose your saves if you update from 1.4 or earlier.
https://github.com/gurrhack/NetHack-Android/tree/v3.6.0-2

**Comment by summonthethunder** [comment] 2016-01-01 19:12
Yes, I'll try it out for you and get back to you.

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Are you willing to try the new release for a while and see if it also crashes?
Keep in mind that you will loose your saves if you update from 1.4 or earlier.
https://github.com/gurrhack/NetHack-Android/tree/v3.6.0-2

-

**Comment by summonthethunder** [comment] 2016-01-01 20:05
Martin,

Tested release 3.6.0-2 for about an hour now, and I no longer experience the crash bug upon loading a saved game (tested 10 times in a row on multiple levels), so that one seems good to go!

However, the command panel bug still remains.  I changed commands via pushing and holding the command panel to make changes, then saved.  Reloaded, and command panel reverts to standard command panel without my changes.

Next, tried setting up new commands via the Command Panel option in the Settings menu, renaming Panel 2 to Command Panel, activating for both portrait and landscape mode.  I also remembered to disable portrait and landscape mode for the Standard Panel set.  Saved, then reloaded, and got the same result of all commands reverting to initial setup, ignoring changes.

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Are you willing to try the new release for a while and see if it also crashes?
Keep in mind that you will loose your saves if you update from 1.4 or earlier.
https://github.com/gurrhack/NetHack-Android/tree/v3.6.0-2

-

**Comment by gurrhack** [comment] 2016-01-01 20:11
Nice!

I'm moving your comment about the command panel over to the other issue

**Closed by gurrhack** 2016-01-01 20:11 UTC

**Comment by summonthethunder** [comment] 2016-01-01 20:13
Ok sounds good.  Thank you again for your help and responsiveness!  Happy New Year!

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Nice!

I'm moving your comment about the command panel over to the other issue

-
