### ISSUE TITLE
Inventory piling and sacrifice

### ISSUE THREAD

**Issue by CJBrew** [gurrhack/NetHack-Android#45] opened 2018-12-06 09:27 UTC
Haven't tested this with vanilla nethack yet.

1) find or create an altar
2) collect at least one (lichen) corpse
3) allow sacrifice time for the corpse to expire
4) obtain (wish/kill) another lichen corpse
5) the new corpse "piles" with the old ones making it impossible to attempt to #offer the new corpse.

**Comment by rpresser** [comment] 2019-04-15 16:12
This was the standard behavior in 3.4.3 vanilla. Similar corpses stack and their "freshness" is averaged.

**Comment by gurrhack** [comment] 2019-05-14 18:39
Closing as "not a bug".

**Closed by gurrhack** 2019-05-14 18:39 UTC
